- src/components/ChecNavigation.vue
Fixing issue that caused navigation to show scrollbars.  
Fixes #222
> [CHEC-767] Fixing issue with visible scrollbars in navigation

- src/components/BaseDropdown.vue
Mentioned in #222 but wasn't spotted in #224
> Update dropdown to not show permanent scrollbars

- src/components/ChecModal.vue
- src/stories/components/ChecModal.stories.mdx
- Removing the ability to close on overlay click
- Removing story that demonstrated this. 
Closes issue #231
> [CHEC-795] Removing ability to close on overlay click

- src/components/ChecHeader.vue
Updating the card variant of the header to match the new designs.
> [CHEC-790] Updating card header variant to new style

- src/components/BaseDropdown.vue
Essentially makes the popover/options list have a `max-height` equal to the bottom px distance of the dropdown-el relative to bottom of the window view-port, thus not allowing it to the exceed the viewport screen. (utilizes https://developer.mozilla.org/en-US/docs/Web/API/Element/getBoundingClientRect)
fixes #211
> [CHEC-787] - Fix bug where Dropdown options (popover) list goes off viewport screen

- src/components/ChecButton.vue
- src/stories/components/ChecButton.stories.mdx
> Ensure a type attribute is not applied to ChecButton if it's a link

- src/components/TextField.vue
solves https://github.com/chec/ui-library/issues/158
> remove offset padding from input when no label provided

- src/components/ChecDatepicker.js
- src/stories/components/ChecDatepicker.stories.mdx
> Ensure datepicker attrbutes are passed correctly to text field component

- package.json
- src/components/ChecDropdown.vue
- src/components/ChecPopover.vue
- src/components/TextField.vue
- src/stories/FormFields.stories.mdx
- yarn.lock
> Simplify dropdown DOM an make styling consistent with text fields

- src/components/ChecDropdown.vue
- src/components/TextField.vue
- src/stories/components/ChecDropdown.stories.mdx
> Add invalid and errored states to dropdowns

- src/components/ChecCard.vue
- src/stories/components/ChecCard.stories.mdx
- src/stories/components/ChecRadio.stories.mdx
- tailwind.config.js
- adds "holo" shadow
- adds hover state to chec-card
> [CHEC-710] - Feature/card hover states

- src/components/ChecDropdown.vue
- src/lang/en.js
> Add missing translation to new search field

- src/components/ChecDropdown.vue
- src/components/ChecOption.vue
- src/stories/components/ChecDropdown.stories.mdx
- src/stories/components/ChecOptionsMenu.stories.mdx
Part 2 of 3 for this issue. Adds a loading indicator to dropdown option lists, and a way to toggle it with a prop
> [CHEC-825] Add loading prop to ChecOption and to ChecDropdown

- src/components/ChecLoading.vue
- src/stories/components/ChecLoading.stories.mdx
> create light, dark variants of chec-loading

- src/components/TextField.vue
- src/lang/en.js
- src/stories/components/TextField.stories.mdx
- Added required prop for toggling native 'required' attribute and targeted styling
*Went with the first option in the task, hope I understood the a/c's correctly*
> [CHEC-841] Add required prop to text field component

- src/components/ChecDropdown.vue
- src/stories/components/ChecDropdown.stories.mdx
Used to trigger the "infinite scroll" functionality that's a part of [CHEC-824]
> Add scroll-to-bottom event in dropdowns

- src/components/ChecVerticalNavItem.vue
- src/components/ChecVerticalNavigation.vue
- src/stories/components/ChecVerticalNavigation.stories.mdx
- Added vertical navigation UI component
- I was running into issues with this early on as I was trying to use options as props and wasn't able to nail down how to detect the active item correctly. With suggestions from Robbie and John, refactored to use Vue router's router link component which has its native active class
- Having trouble trying to figure out alternatively how to programmatically push the routes https://router.vuejs.org/guide/essentials/navigation.html#programmatic-navigation in order to add keyboard events (I have not added keyboard events) <- would love some help on this if this is part of a/cs
> [CHEC-842] Feature/vertical nav

- src/components/ChecDropdown.vue
Fixes https://github.com/chec/ui-library/issues/190
> ChecDropdown no longer accepts value attributes that do not exist in the options attribute

- src/index.js
- src/mixins/dropzone.js
Fixing export, and the prop type (and docs)
> Minor uploader bugfixes

- src/components/ChecVerticalNavItem.vue
- src/stories/components/ChecVerticalNavigation.stories.mdx
Fixes https://github.com/chec/ui-library/issues/307
> Remove extraneous markup from vertical navigation and ensure story reflects active state

- src/components/TextField.vue
- src/stories/components/TextField.stories.mdx
> Restore placeholders in text fields

- src/components/ChecAccordion.vue
- src/stories/components/ChecAccordion.stories.mdx
Couldn't really figure out a nice way to do this without moving it to JS. 😞 
Fixes https://github.com/chec/dashboard/issues/274
> Fix collapsed accordion bottom margin

- src/components/TextField.vue
- src/stories/components/TextField.stories.mdx
Making the input padding dynamic for currencies. 
Solves #328
> Making input padding dynamic based on currency

- src/assets/tailwind.css
- src/components/ChecCheckbox.vue
- src/components/ChecDataPill.vue
- src/components/ChecRadio.vue
- src/components/ChecSwitch.vue
- tailwind.config.js
As I was going through the backlog, there were some super simple UI lib updates that I just did as I came across them:
- Update inset shadow and add to checkboxes, radios, and switches
- Update mono font to "Source Code Pro"
- Update data pill colours
- Add 6xl font size
Fixes CHEC-772
Fixes CHEC-770
Fixes CHEC-798
Fixes CHEC-840
> Various UI lib updates from design iteration

- src/components/ChecButton.vue
- Fixing hover text colors
- Adding pointer to link tag type 
- Fixing bg color to better match designs on hover
Solves #309
> Fixing inconsistent button hover states

- src/components/ChecDropdown.vue
> Fixing Placeholder dropdown padding issue

- src/components/ChecButton.vue
- src/stories/components/ChecButton.stories.mdx
Required for the new design for the delete button in add product
> Add "text" (or "label") button style/variant

- src/components/ChecTable.vue
- src/index.js
- src/stories/components/ChecTable.stories.mdx
- src/stories/styles/tables.stories.mdx
Adding table component so we can have prepends
> [CHEC-980] Table component w/ prepend

- src/components/ChecAccordion.vue
Hi Chec team,
From what I understand, this is what should be done from #226. If there's more to do, please let me know!
Closes #226
> Change ChecAccordion Heading color to gray-600

- src/components/ChecTag.vue
- src/stories/components/ChecTag.stories.mdx
> [CHEC-977] Update tag styling

- package.json
- src/components/ChecAccordion.vue
> Add and implement ResizeObserver polyfill

- src/components/ChecDropdown.vue
- src/components/ChecOptionsMenu.vue
- src/components/ChecPopover.vue
- src/stories/components/ChecOptionsMenu.stories.mdx
- src/stories/components/ChecPopover.stories.mdx
Update the options menu and dropdown components to use new shared API provided by the popover componet
Add a story for the popover component
> [CHEC-1001] Extract shared popover logic to popover component

- package.json
- src/components/CodeBlock.vue
- src/components/CodeBlockGroup.vue
- src/stories/components/CodeBlock.stories.mdx
- yarn.lock
- Updating to new package to allow for line numbers.
- Introducing code block group component.
> [CHEC-968] Code block groups

- src/components/ChecAccordion.vue
Fixes #212 
Swapped out toggle div to use ChecButton which fixes keyboard accessibility
> Change icon div to ChecButton to fix accessibility of accordion toggle

- src/components/ChecImageManager.vue
- src/mixins/dropzone.js
- src/stories/components/ChecImageUploader.stories.mdx
- Adding user-defined maximum file limit.
- Adding a 2 column layout needed in the sidebar
- Adding responsive for 4 column layout.
**2 Column:**
**3 file max:**
> Image manager adding max file limit and alternative column structure

- src/components/ChecAccordion.vue
- src/stories/components/ChecAccordion.stories.mdx
Updating the accordion styling to match updated designs.
> Updating accordion styles

- src/stories/components/ChecAccordion.stories.mdx
Adding back in the card example for accordions as per comment in #377
> Re-adding removed card example for accordions

- src/components/ChecThumbnailCard.vue
- src/index.js
- src/stories/components/ChecThumbnailCard.stories.mdx
Adding thumbnail card component.
@dvnkshl @blazepollard I took some liberties when putting this component together due to the time restraint and need for light variants. Let me know if anything needs to be tweaked. 
**Light Variant:**
**Dark Variant:**
**Fallback:**
> [CHEC-1094]Thumbnail Card

- src/components/ChecDivider.vue
- src/stories/components/ChecDivider.stories.mdx
Part of chec/marketing-chec#471
> Add dark variant of dividers

- src/components/ChecTab.vue
- src/stories/components/ChecTab.stories.mdx
- yarn.lock
Part of chec/marketing-chec#465
> Update tabs with more dark/light variants

- src/components/ChecWysiwyg.vue
- src/stories/components/ChecWysiwyg.stories.mdx
> Fix bug where WYSIWYG content couldn't be externally changed without a re-render

- src/components/ChecSlideoutPanel.vue
- src/components/ChecSlideoutPanel/Overlay.vue
- src/components/ChecSlideoutPanel/Panel.vue
- src/components/ChecTable.vue
- src/components/TextField.vue
- src/index.js
- src/stories/components/ChecTable.stories.mdx
While working on new features in the dashboard I've found some bugs and wanted some new features:
- Add filter bar to exports
- Add a "snug" variant to tables
- Make z-index on panels lower so tooltips & popovers work
- Fix currency symbol in text fields without a label
> A few updates/fixes

- src/components/ChecSlideoutPanel/Panel.vue
> Add overflow scroll and shadow to footer in panel

- src/components/ChecSlideoutPanel/Panel.vue
Sorry, need to revert the z-index as stacking panels were layered under
> Remove z-index on header and footer in panel

- src/components/ChecDataPillGroup.vue
- src/stories/components/ChecDataPill.stories.mdx
Fixes https://github.com/chec/dashboard/issues/722 and fixes https://github.com/chec/dashboard/issues/739
> Fix bug where long data pill labels would break over multiple lines when in a group

- src/components/ChecDataPillGroup.vue
Fixes https://github.com/chec/dashboard/issues/727
> Vertically center text in data pill groups and left/right align either side

- src/stories/styles/misc.stories.mdx
- tailwind-plugins/hazardBorder.js
- tailwind.config.js
I've built this in a way that will allow us to have some variants in the future if we want. The one right now uses a combination of grays so it's called "gray".
> Add tailwind plugin for hazard borders and add a story showing it off

- src/components/ChecDropdown.vue
- src/components/ChecFilterBar.vue
- src/components/ChecFilterBar/FilterList.vue
- src/components/ChecFilterBar/FilterPanel.vue
- src/lang/en.js
- src/stories/components/ChecFilterBar.stories.mdx
Fix an issue with dropdown widths for dropdowns that appear in popovers
Fix label issues with filters
Part of https://linear.app/trychec/issue/CHEC-1453/add-search-bar-and-filters-to-orders-view
> Support date range and dropdown filters in the filter bar

- src/components/ChecFilterBar.vue
- src/components/ChecFilterBar/FilterList.vue
Clear search when clicking the clear all button
More UI lib stuff to come
> Prevent search from clearing when applying filters

- src/components/ChecLineChart.vue
- src/stories/components/ChecLineChart.stories.mdx
Fixes an issue I forgot to raise apparently :see_no_evil:
> Consider window scroll when positioning tooltips on graph points

- src/components/ChecFilterBar.vue
- src/components/ChecFilterBar/FilterPanel.vue
- src/lang/en.js
- src/stories/components/ChecFilterBar.stories.mdx
Add an option to include headers in the filter panel
Resolves #448
> Adjust filter panel styling to match figma

- src/components/ChecAlert.vue
- src/stories/components/ChecAlert.stories.mdx
Follow up to https://github.com/chec/marketing-chec/pull/587 for a purple alert color
cc @eufandem
> Add new alert state in purple for news/announcements alerts

- src/components/ChecTab.vue
> Add missing button type attr to ChecTab

- src/components/ChecButton.vue
> Add enabled pseudo to prevent hover style on disabled links

- src/components/ChecNotification.vue
Fixes https://github.com/chec/ui-library/issues/454
> Ensure long text breaks in notifications

- src/components/ChecSlideoutPanel/Panel.vue
> Fixing issue with slide out panel showing horizontal scroll

- src/components/ChecDropdown.vue
Fixes https://github.com/chec/dashboard/issues/844
> Add defensive check for this.value existing before checking its length

- src/components/ChecDropdown.vue
- src/stories/components/ChecDropdown.stories.mdx
> Prevent arrow on dropdown from shrinking and add minimum gap between the value and arrow

- src/components/ChecAlert.vue
> Updating alert links to be readable.

- src/components/ChecAlert.vue
> Adding underline on hover of link in alerts

- src/components/ChecTagsField.vue
- Remove absolute positioning on input to drop to new line if multiple tags present
Fixes #483 
Fixes #486
> Remove absolute positioning on input 

- src/components/ChecTag.vue
- src/components/ChecTagsField.vue
Fixes #484 
Fixes #500 
Silly me, originally went for this unconventional fix and took me longer than it should have. Fixed now
> Add focus event for keyboarding

- src/components/ChecVerticalNavigation.vue
- src/stories/components/ChecVerticalNavigation.stories.mdx
Adding inline variant of the vertical navigation.
**Screenshots:**
> Adding inline variant of vertical navigation

- src/components/ChecAlert.vue
> Add flex shrink 0 to svg icon

- src/components/ChecModal.vue
- src/stories/components/ChecModal.stories.mdx
https://airtable.com/tbl2iEQph7UCFhn7u/viwf9gVChMZmW015T/recpbAGsJkhsK82By?blocks=hide
Fixes #164
> Add dismiss on modal overlay, edit default width on modal

- src/components/ChecCard/InnerBlock.vue
Fixes https://github.com/chec/dashboard/issues/1172
> Remove flex to fix overflow issue in inner block

- src/components/ChecCheckbox.vue
- src/stories/components/ChecCheckbox.stories.mdx
Not sure what I was thinking with this last pr https://github.com/chec/ui-library/pull/543 on adding required styling. This PR is a follow up to fix that and add an error state
> Edit incorrect required prop, add error state

- src/components/ChecAlert.vue
Fixes https://github.com/chec/dashboard/issues/1400
> Fix bug where anchor buttons inside alerts were using text anchor styles on hover

- src/components/ChecDropdown.vue
Fixes https://github.com/chec/ui-library/issues/569
> Add (required) to end of dropdown label when it is required

- src/components/ChecRadioGroup.vue
> Fix bug where required attributes on radio groups passed to wrong element, and add suffix to label

- src/assets/tooltips.scss
Allow tooltips to have line breaks with i18n json using `/n`
> Allow tooltips to have line breaks with i18n json

- src/components/CodeBlock.vue
- Removing Prismjs theme and incorporating it into the component
Closes #563
> Removing prismjs theme and incorporating it into the component

- src/components/ChecAccordion.vue
- src/stories/components/ChecAccordion.stories.mdx
This was annoying me in the FAQ on the docs site.
> Allow accordions to be toggled when clicked. Make emitted event consistent

- src/components/ChecCard.vue
- src/stories/components/ChecCard.stories.mdx
- src/stories/components/ChecCard/InnerBlock.stories.mdx
Will update dashboard and marketing site after this merge and release
> Edit shadow prop to have shadow by default

- src/components/ChecChart/PieWrapper.vue
- src/components/PieChart.vue
- src/stories/components/PieChart.stories.mdx
> Add pie chart

- src/components/ChecDropdown.vue
Fixes https://github.com/chec/ui-library/issues/595
> Fix alignment issue when dropdowns do not have a label but do have selected values
