- src/components/ChecNavigation.vue
- src/stories/components/ChecNavigation.stories.mdx
See the storybook for an example where this was an issue previously
> Force navigation item text to not wrap onto new lines

- src/components/TextField.vue
This was my opinionated addition, and it's pretty annoying for most people.
> Remove auto-selecting text when focusing text fields

- src/assets/mixins.scss
- src/assets/tailwind.css
- src/components/ChecAvatar.vue
- src/stories/components/ChecAvatar.stories.mdx
- this PR implements the aspect-ratio mixin within chec-avatar, making it possible to render a responsive 1:1 aspect-ratio avatar, I added a story to demonstrate the use-case.
Here's a screenshot from the story. This helps out making the avatar a bit responsive, currently need this in the beta dashboard for the user content on the nav, when it hover/expands.  (see https://github.com/chec/dashboard/pull/123#issuecomment-650310396 for a screenshot of the user-content overflowing)
> implement aspect-ratio in avatar component

- src/components/ChecModal.vue
- src/stories/components/ChecModal.stories.mdx
- Added Box Shadow
- Added light overlay with option to use either light or dark.
Note: 
This PR does not include removing the close button as I need to verify with the design first. Since we are removing the ability to close by clicking off the modal we may be getting ourselves into a bit of a UX footgun.
> [CHEC-796] Updating Modal Overlay 

- src/components/BaseDropdown.vue
- Need to clarify if this task is only to update to ChecIcon and flip on active. Looks like the popover option menu was changed to the ellipsis icon so I didn't apply to that
- Was a bit confused on BEM structure here, not sure if i applied the open state correctly on the svg as if you click right on the svg path, dropdown doesn't toggle. But if on dropdown control field and icon area, dropdown does toggle
> [CHEC-716] Update dropdown icon to flip on active

- .eslintignore
- src/components/ChecAccordion.vue
- src/stories/components/ChecAccordion.stories.mdx
**Issue:**
Accordions rely on `overflow: hidden` on the body to work, this is causing the cards box-shadows to be clipped when placed inside of an accordion.
**Changed:**
- Added `index.stories.js` to the `.eslintingnore` due to an issue that required you to save the file each time you saved any other file.
- Modified accordion to gave the padding in the body so the box-shadow is not clipped.
- Added a new story showing cards in an accordion.
**Potential Technical Debt:**
The body container will now animate up while the accordion is being closed. This had to be done to make sure the padding between the header and body is correct.
Fixes chec/dashboard#183
> [CHEC-797] Fixing accordion to not clip card shadow.

- src/components/ChecIcon.vue
- tailwind-plugins/iconSize.js
- tailwind.config.js
I've been missing something like this every time I've used an icon inline with text, so here's an option to specify the size as a prop. This adds a tailwind plugin that generates `icon-[size]` tailwind "utilities" to set the width/height to match the font size.
> Add icon size prop to ChecIcon in line with font size

- src/components/TextField.vue
The problem was that the label was actually covering half the input, and we were using a `:before` psuedo-element to actually render the text. I couldn't figure out why we did this, so I've refactored it to use the actual label, and made it only as big as it's contents. I also fixed up the alignment so that it's correctly aligned with the text field value.
Fixes chec/dashboard#53
> Refactor label to not cover half the input

- package.json
- src/components/ChecDropdown.vue
- yarn.lock
Fixes #260
Apparently a known issue with the simple-portal package: https://github.com/LinusBorg/vue-simple-portal/issues/38
Was trying to avoid the heavier and more versatile library as creating "portal targets" is hard to do in a UI library. Hidden in their hard to navigate docs I found `MountingPortal` which does what we want. https://portal-vue.linusb.org/guide/advanced.html#rendering-outside-of-the-vue-app
> Replace simple-portal with portal-vue

- src/components/TextField.vue
- src/stories/components/TextField.stories.mdx
Part 1 of 3 for this issue. Allows putting a left aligned icon in a text field. See https://www.figma.com/file/QapWtySLg7GOXEdGcTFVDZ/Global-components?node-id=953%3A135
> [CHEC-825] Allow specifying an icon to show in text inputs

- src/components/ChecDropdown.vue
- src/components/TextField.vue
- src/stories/components/ChecDropdown.stories.mdx
Final part of CHEC-825. Allows the display of a search text area in a dropdown options list. This doesn't actually do filtering, as it's up to the implementation to handle the input events and update the list of options (which is a prop).
> [CHEC-825] Add search box to dropdowns

- src/components/ChecAccordion.vue
- src/components/ChecSwitch.vue
- src/lang/en.js
- src/stories/components/ChecAccordion.stories.mdx
I've also:
- tried to smooth out the animations a bit (again) - although it's still a bit janky if you spam the button. I've checked that the cards in accordions use-case is unaffected.
- added the button label to the "title" attribute on the existing toggle button - hopefully improving accessibility
- Added an option to prefix the label on a switch, which is coming up a bit in new designs
This is out of cycle work. I'm supposed to be scoping the add product work. I can't help getting a bit bored though :slightly_smiling_face:. The new add product designs use this pattern (https://www.figma.com/file/og79WKi1zrrBgZWayZY4ik/Dashboard-Web?node-id=4196%3A52776). The accordion designs in Figma don't show this option, but the component is an accordion in Figma, so I assume that Blaze expected …
> Add "variants" to accordions, allowing different toggle types

- src/components/ChecNotification.vue
- src/stories/components/ChecNotification.stories.mdx
- Adding margin for buttons passed through the notification slot.
- Slightly cleaning up padding as it was inconsistent with designs.
- Adding story to demonstrate a notification with a button passed in it.
> Adding margin for buttons passed in notification slot

- src/components/ChecDropdown.vue
- src/components/TextField.vue
- src/stories/components/TextField.stories.mdx
- tailwind.config.js
**Changes:**   
- Adding in the Hover and Active updates
- Adding in the dark version for text fields
**Note:**
I'm dictating it through a new prop called `styleVariant`.  The reasoning for this is the error and disabled states are considered variants. I think we may want to take a look into how this component is structured in the future as a state is probably not a variant. I left variant untouched so as to not cause issues with integrated code. 
**Screenshots:**
> [CHEC-861] Updating Input Hover, Active and dark versions

- src/components/TextField.vue
- src/stories/components/TextField.stories.mdx
Added a currency prop that shows a dollar sign before the input. Value will still be unaffected. Down the line, we could make it so the symbol is definable programmatically but for now, I have included it as a prop.
> [CHEC-915]  Modify textfield to have currency type

- src/components/ChecFileUploader.vue
- src/stories/components/ChecFileUploader.stories.mdx
This PR allows you to create an asynchronous function that resolves a URL where a file should be uploaded, and provide that to the `endpoint` prop instead of a constant URL.
> [CHEC-899] Add the ability to dynamically issue URLs for ChecFileUploader

- src/components/ChecPaginate.vue
I spent a few minutes looking for a bug here, so this improves the docs
> Add docs for the pageSizeOptions prop to note that it filters out unneeded values

- src/components/ChecCheckbox.vue
Previously were fixed to their absolute position
Fixes https://github.com/chec/ui-library/issues/285
> Checkbox ticks in multiselects now scroll with everything else

- package.json
- src/components/ChecImageManager.vue
- src/components/ChecImageManager/ImageBlock.vue
- src/lang/en.js
- src/mixins/dropzone.js
- src/stories/components/ChecFileUploader.stories.mdx
- src/stories/components/ChecImageUploader.stories.mdx
- yarn.lock
I've done some stuff to get the drag image to not be too large, and I've run the on-the-fly design of the drop placeholder and the changes to the image fit past Blaze.
> Add the ability to drag & drop sort images in the image manager

- src/components/ChecTag.vue
- src/components/ChecTagGroup.vue
They currently conflict with anything else we use that has "tag" classes applied to it, e.g. Prism syntax highlighting
> Make Tag and TagGroup classes more unique

- src/components/ChecCard/InnerBlock.vue
- src/components/ChecDropdown.vue
- src/components/TextField.vue
- src/stories/components/ChecDropdown.stories.mdx
- src/stories/components/TextField.stories.mdx
Adding option to allow text fields and dropdowns to have an always minimized label. This is necessary for the shipping options section.
> Dropdown & textfield force minimized label option.

- src/components/ChecAccordion.vue
- src/components/ChecFileUploader.vue
- src/components/ChecImageManager.vue
- src/components/ChecImageManager/ImageBlock.vue
- src/mixins/dropzone.js
- src/stories/components/ChecFileUploader.stories.mdx
- src/stories/components/ChecImageUploader.stories.mdx
- Add an event that's emitted when accordions are toggled
- Refactor file/image uploaders to manage in-progress state internally
Most of the file stuff was brought about when I tried to use the components in place for the first time. I think the work I've done here covers most of the use-cases.
> Update file uploading (and minor accordion enhancement)

- src/components/ChecAccordion.vue
- src/components/ChecDropdown.vue
#312 did this for text fields which was a bit of a functional requirement. This wasn't so pressing, but keeps feature parity between the two different fields.
> Restore placeholders to dropdowns

- src/components/ChecFileUploader.vue
- src/components/ChecFileUploader/FileRow.vue
- src/components/ChecImageManager.vue
- src/components/ChecImageManager/ImageBlock.vue
- src/lang/en.js
- src/mixins/dropzone.js
I also added title attributes to the delete button since they are otherwise just an icon, and a type="button" attribute to ensure they do not post a form they are wrapped in by mistake (as seen in the Storybook).
> Images and files in manager/uploader can now be deleted

- src/components/ChecFileUploader/FileRow.vue
- src/components/ChecImageManager/ImageBlock.vue
When you delete an image/file while it's uploading, it comes back when it finishes uploading. This is a fix for that by hiding the delete button while the file is uploading.
> Image and file upload delete buttons are now hidden while files are uploading

- src/components/ChecCard/InnerBlock.vue
Adding flex-grow to solve issue causing repeated fields to not be full width if an action is on the right side.
Solves #301
> Adding flex grow to solve InnerBlock full width issue.

- src/components/TextField.vue
- src/stories/components/TextField.stories.mdx
Zero will now show the currency icon if the field is a currency type.
Solves #318
> Allowing zero to show currency field

- src/lang/en.js
Removing double S from add image button in media manager
> Removing double S from add image button in media manager

- src/components/ChecButton.vue
- src/components/ChecTag.vue
- src/stories/components/ChecTag.stories.mdx
- Updated the tag button to the square variant now used for tag groups
- Removed the light grey tag type as per discussion with Blaze (It will default to the whit type if used).
Resolves #351
> [CHEC-977] Updating tag button style, removing light grey tag type

- src/assets/svgs/MIcons/ic-checkout-flat.svg
- src/assets/svgs/MIcons/ic-code-flat.svg
- src/assets/svgs/MIcons/ic-hosted-flat.svg
- src/lib/icons.js
Adding the new marking icons for the Slider block.
> Marketing icons for slider block

- src/components/PasswordField.vue
- src/stories/components/PasswordField.stories.mdx
Fixes a regression where this was no longer possible.
Part of https://github.com/chec/dashboard/issues/447
> "Show password" action button may again be hidden from PasswordFields

- src/components/ChecOptionsMenu.vue
- src/components/ChecPopover.vue
- Ensure correct DOM node is used for popper.js
- Add menu name to MountingPortal
- Ensure popper target ref exists before use with poppoer.js
Part of fixing the cypress tests for chec/dashboard#463 and fixing the ui-library for use in the dash.
> Minor popover bugfixes

- package.json
- src/components/ChecPopover.vue
- yarn.lock
This component needs to be given a ref to position the popover against, and it expecs a ref name. The problem is that refs created with Vue can actually result in an array of refs. This PR ensures that we support JSON prop notation for accessing attributes (eg. `prop[0].thing`).
> Allow accessing array based refs with ChecPopover

- src/components/ChecButton.vue
If a button is set as a router link and also disabled, the button will still function. Natively, Vue router does not support disabling router links. A work around to this is to set the event from "click" to "" to achieve the desired effect.
> Removing event prop on router links if button is disabled

- src/components/TextField.vue
Color input type was not showing the selected value. 
**Before:**
**After:**
> Height override so color value shows correctly

- src/components/TextField.vue
If no label is present, the value will be centered in the input.
> Centring value if no label preset in text field

- src/components/CodeBlockGroup.vue
Updating padding when code blocks are showing logo reel.
> Updating padding on code block group if logo reel is visible

- src/components/ChecButton.vue
- src/stories/components/ChecButton.stories.mdx
Adding outlined button option needed for marketing site.
**Light BG:**
**Dark BG:**
> Adding outline button option

- src/components/CodeBlockGroup.vue
Part of https://github.com/chec/marketing-chec/issues/481
If we're not happy with this adjustment then we'll need to get our hands dirty with the border radius on the background of the code block tabs. It's currently "rounded-full" which doesn't really work when it splits into two lines. Would need to be a specific number that works instead e.g. 200px or something.
This change prevents the home page on the marketing site from splitting over two lines.
> Reduce left margin on small viewports for code block tabs to prevent line wrapping

- src/components/ChecThumbnailCard.vue
Part of https://github.com/chec/dashboard/issues/534
> ThumbnailCards are now all the same height as each other when used in a grid

- src/mixins/dropzone.js
If an image was preloaded and the max files set to 1, the user could not replace the image as it would set the max files to 0. 
this closes chec/dashboard#523 and chec/dashboard#511
> Couldn't upload images if max was 1 if an image was pre loaded

- src/components/TextField.vue
Fixes error:
```
ui-library.common.js?9c71:53689 Uncaught TypeError: Cannot read property 'clientWidth' of undefined
at VueComponent.adjustSlotWidth (ui-library.common.js?9c71:53689)
```
> Fix null pointer error on rightContentSlot ref

- src/components/ChecThumbnailCard.vue
Updating the Dark mode thumbnail color to match the updated design for Ray's listing.
> Updating thumbnail card dark mode color

- .stylelintrc.json
- src/components/ChecButton.vue
- src/components/ChecDropdown.vue
- src/components/ChecFilterBar.vue
- src/components/ChecFilterBar/FilterList.vue
- src/components/ChecFilterBar/FilterPanel.vue
- src/components/ChecFilterBar/Search.vue
- src/components/ChecPopover.vue
- src/components/ChecSwitch.vue
- src/components/ChecTag.vue
- src/components/ChecTagGroup.vue
- src/lang/en.js
- src/stories/components/ChecFilterBar.stories.mdx
Also:
- Add an "input" style for buttons that look like an input
- Allow custom IDs (and labels) for the switch component
- Fix missing BG colour on "white" tags
- Allow reset text to be customised in tag groups
This also closes [CHEC-1000]
See the designs I've been following here: https://www.figma.com/file/QapWtySLg7GOXEdGcTFVDZ/Global-UI?node-id=9075%3A12122
> [CHEC-1311] Add filter bar component

- src/components/ChecVerticalNavigation.vue
The padding was actually in the designs, and is important for the active state of menu items. I have added it back but at a size that looks even with the x padding.
> Partial revert of 8e490c59aef3569fa6649cca0d68121e17094858, adding some padding back

- .github/workflows/build-bundle.yml
Localazy requires node >=11, this change updates the action we use
> Update actions-yarn to version that uses node@lts

- .stylelintrc.json
- package.json
- src/assets/mixins.scss
- src/components/ChecImageManager.vue
- src/components/ChecImageManager/GalleryModal.vue
- src/components/ChecImageManager/ImageBlock.vue
- src/components/ChecModal.vue
- src/components/ChecOptionsMenu.vue
- src/lang/en.js
- src/stories/components/ChecAvatar.stories.mdx
- src/stories/components/ChecImageUploader.stories.mdx
- yarn.lock
There's two key updates here:
- You can now specify a list of existing images which powers the functionality of a "choose existing" button. 
- You can provide additional "actions" that can be performed on each image. Providing these will change the existing delete button into a more options menu
There's one more part to the image management UI in the designs - relating to providing fields for updating attributes on an individual image. I've been debating with myself whether this is a good idea to add to the UI library though. It's true that we can ecapsulate the functionality of showing the modal and displaying the image, but we'd need to provide a slot for the fields.
I'll discuss a little more with the team and follow up with another PR
> [CHEC-1357] Add functionality to the image manager component

- src/components/ChecImageManager.vue
- src/components/ChecOption.vue
Some issues I discovered trying to integrate the new functionality of the image manager during [CHEC-1377]
This time I broke out `yarn link` to double check everything is working.
> Ensure "normalised" files are used internally by the image manager

- src/components/ChecFilterBar.vue
- src/components/ChecFilterBar/FilterList.vue
- src/components/ChecFilterBar/Search.vue
- src/stories/components/ChecFilterBar.stories.mdx
While @jaepass was testing an implementation of the filter bar on the dashboard, she noted some UX quirks around filtering. This PR adds tracking for the "active" text search in the filter bar, and controls to clear that search.
> Fix UX issue with unclear active text search on filter bar

- src/components/CodeBlockGroupIcon.vue
- ~~Adding toggle for opening code block icon links in a new tab~~
- Dynamically changing tag type depending on the link given. If no link is given, the tag defaults to span.
> Adding toggle for opening code block icon links in a new tab

- src/components/ChecTagsField.vue
This was annoying me a little as I'd have to hit tab twice to get to the actual text area when using this in a form.
> Remove tab index on tags field so the text input inside is the next tabbable input

- src/components/ChecAlert.vue
- src/stories/components/ChecAlert.stories.mdx
As per discussion with @dvnkshl, the info alerts are not noticeable when set to inline because of the grey coloring. Updating it to our blue to make it more noticeable. 
**Preview:**
From
To
**Example Integration:**
From
To
> Updating info alert to be more noticeable

- src/components/ChecTab.vue
Added new focus/pressed state styles in ChecTab design so it differs slightly from the hover state
Ref: https://www.figma.com/file/QapWtySLg7GOXEdGcTFVDZ/Global-UI?node-id=7482%3A85
Closes #385
> Add new focus state styles to ChecTab

- src/components/ChecOptionsMenu.vue
I'm lazily loading the contents of the options menu, but it's not possible right now as I can't tell when the menu is being opened.
> Add a click event to the options menu button

- src/components/ChecAlert.vue
- src/stories/components/ChecAlert.stories.mdx
Ideally this uses BEM classes instead of `svg` targetting specifically, but the ChecIcon component has a custom render method and I didn't want to spend too much time trying to get custom classes to be passed through, so this is a quick fix.
> Fix bug with icons inside buttons in alerts being given incorrect text colour

- src/components/ChecSlideoutPanel/Panel.vue
Fixes #492 
Tried to add z-index to header and footer but we would run into issues of nested panels. Fixed by applying border top and bottom, I think this looks subtle and addresses the issues.
> add min height to header footer and add border top and bottom

- src/components/ChecTagsField.vue
- src/stories/components/ChecTagsField.stories.mdx
Fixes #499
Tags will now not be added if input is unfocused/blurred and will only be added on outside click if `addOnBlur` is set to true. Did not change the `addOnBlur` prop name as component is being used in the dashboard.
> Remove blur detection handler, add tag on outside click

- src/components/ChecModal.vue
- src/stories/components/ChecModal.stories.mdx
As part of the UX audit, buttons are on the right now. I haven't really considered instances where we want exceptions to this rule, but we can deal with that when it becomes an issue.
> Align buttons in modal toolbars to the right

- src/components/ChecFilterBar/Search.vue
- src/stories/components/ChecFilterBar.stories.mdx
The variants search filters for validity have been broken for a while because they assumed extra filter information wouldn't be dropped. I think this broke after it the filters for variants were changed so they don't break with non-english locales. I also added an "id" to the text search filter, so that can be used instead of checking the localised string to identify the filter.
> Update filters applied through search bar to not drop filter metadata

- src/components/ChecSlideoutPanel.vue
Fixes https://github.com/chec/ui-library/issues/524
Can be tested using the "Slideout panel > With content" story if you reduce your viewport vertical height so the content scrolls vertically, then scroll down a little.
> Fix bug where slideout panel header shadow would position underneath the content

- src/stories/components/ChecModal.stories.mdx
There is a `ml-2` applied to the last button in this example but the zero padding makes it look weird. I've removed this from the example to make it more real world.
> Remove p-0 from toolbar in modal example to more accurately represent its use

- src/assets/tooltips.scss
The tooltip component is not a native UI lib component and it does not have a width prop so I've set a max width and line height as the solution to longer content.
Example of longer content with width:
> [CHEC-1736] Add max width and line height to tooltip

- src/components/ChecCard/InnerBlock.vue
Fixes https://github.com/chec/dashboard/issues/1281
- Previously the action button was outside the title and content container, so I've changed it to be similar to other patterns of title and action headers where the action button is aligned far right. 
Example of dashboard implementation
With action button:
No action button:
Narrow screen with action button:
> Flex action button with inner block title

- src/components/ChecRadio.vue
ChecRadioGroups radio options would be rendered as undefined because of some old code that required the label to be passed as a slot.
> Fixing an issue where the radio options label would be rendered as undefined

- tailwind.config.js
- Updating the green colors to help make the hover state on buttons less jarring.
**New colors;**
green-600 to green-100
**Screenshot:**
The larger button is hovered.
> Tweaking colors for making hover less jarring

- src/components/ChecSwitch.vue
Forgot to update the switch color to match the darker green. Now looks better with buttons.
> Updating switch color to match updated button green

- src/stories/components/ChecAlert.stories.mdx
Fixes https://github.com/chec/ui-library/issues/562
> Fix bug where apostrophes were HTML encoded in ChecAlert storybook example

- src/components/ChecLoading.vue
- src/components/ChecSlideoutPanel.vue
With https://github.com/chec/dashboard/pull/1488 fix, the slideout panel would be under the nav header and sidebar. This PR fixes that.
Fixes #565 as well
> Increase z-index of panel

- src/components/ChecDropdown.vue
Put a reasonable max height for dropdowns that doesn't just rely on viewport size
> Enforce a max option height for dropdowns

- src/components/ChecDropdown.vue
- src/components/ChecOption.vue
- src/stories/components/ChecDropdown.stories.mdx
Fixes:
- Dropdown labels appear under the dropdown arrow
- Dropdown values overflow the dropdown
- An issue where labels overlayed the selected value
Added:
- The ability to specify whether you want the dropdown to expand on the y-axis
Also:
- Put some stuff in alphabetical order
Fixes #573
> Fix overflowing labels and values in dropdowns

- src/components/ChecTag.vue
- src/stories/components/ChecTag.stories.mdx
Realized that this isn't actually a button so I removed the hover states outright. Issue confused me but I can't find an instance where these are clickable as a router link. 
Closes #555
> Removing hover, focus and active from tags

- src/components/ChecDropdown.vue
- src/components/ChecFilterBar.vue
- src/components/ChecFilterBar/Search.vue
- src/components/ChecOptionsMenu.vue
- src/components/ChecPopover.vue
- src/stories/components/ChecPopover.stories.mdx
Due to the [caveats](https://portal-vue.linusb.org/guide/caveats.html) of `portal-vue`, you might just want to use the "popper" functionality of a popover, without moving the DOM to a root node. This makes that possible.
> Make usage of portals optional when using ChecPopover

- package.json
- src/mixins/dropzone.js
- yarn.lock
The new major version fixes a bug where the bundle relies on window (they've dropped "autodiscover" which did this). 
They've also dropped IE support, but I think we're okay with this.
> Update dropzone to new major version

- src/components/ChecCard.vue
- src/stories/components/ChecCard.stories.mdx
- src/stories/components/ChecCard/InnerBlock.stories.mdx
- Add new borders style, remove unused vertical and horizontal styles
- Add background as prop
- Add shadow as prop
Follow up PR with marketing card Contentful model edits
Reimplement dashboard and marketing site with new props
> [CHEC-1932] Add new borders, background, and shadow props

- src/components/ChecToast.vue
Fixes https://github.com/chec/ui-library/issues/594
> Fix long overflowing text in toasts, for example when using a long email address
